apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zdh2n9d9f-go
  janus-idp.io/tekton: zdh2n9d9f-go
  backstage.io/kubernetes-id: zdh2n9d9f-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zdh2n9d9f-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
